[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SphericalSBPOperators = "54f2a669-6442-4ec9-9f33-60161b4634ca"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"

[sources]
SphericalSBPOperators = {path = ".."}

[compat]
Documenter = "1"
SummationByPartsOperators = "0.5"
